### ISSUE TITLE
Test build bugs: Batch 2

### ISSUE THREAD

**Issue by Totemaster** [StarStorms21/JurassicSaga-Bugs#10]
- Tall multi-segment plant colour glitch on the bottom segment.
- There weren't any mosquitoes in the Carboniferous. Rename the amber to "Carboniferous arthropod segments in Amber". The idea is that in this particular era, these are pieces of the actual giant bugs themselves in amber, rather than blood sucked from them.
- There weren't any mosquitoes in the Permian either. Rename the amber to "Permian Bloodsucker in Amber", for some ambiguity. Mosquitoes wouldn't have been around until at least the Late Triassic, but in this mod we're assuming that there might have been some kind of insect or tick around before that with a similiar niche, for gameplay reasons.
- "Cultivated" eggs don't really need the "cultivated" part in their names if they drop from an actual mob. Spiders, salmon, etc.
- You shouldn't be able to walk on Cobbania. It's too small and weak.

**Comment by StarStorms21** [comment]
all fixed!
