### ISSUE TITLE
Bug report: New crash

### ISSUE THREAD

**Issue by Totemaster** [StarStorms21/JurassicSaga-Bugs#12]
- The game crashed when I tried to break a Zingiberopsis with water.
[crash-2021-06-18_19.17.25-client.txt](https://github.com/StarStorms21/JurassicSaga-Bugs/files/6678935/crash-2021-06-18_19.17.25-client.txt)

**Comment by StarStorms21** [comment]
related; all zingiberopsis seem to drop as the default colour when breaking them with water

**Comment by StarStorms21** [comment]
fixed for now, leaving open so i remember to test server side!
