### ISSUE TITLE
Test build bugs - Batch 1

### ISSUE THREAD

**Issue by Totemaster** [StarStorms21/JurassicSaga-Bugs#6]
- Animal fossils should be a bit more common from fossil ore.
- Cobblestone should be a bit less common from fossil ore.
- Cobbania placement could work more like a lilypad: I.e. not dependent on being planted up against a block.
- Got a Meganeura fossil from Late Cretaceous fluvial fossil ore. It should be Carboniferous and Permian.
- Got a Cearadactylus fossil from Late Cretaceous fluvial fossil ore. It should be Mid Cretaceous.
- Got an Apatosaurus fossil from Late Cretaceous fluvial fossil ore. It should be Jurassic.
- Got Parasaurolophus fossils from Jurassic fluvial fossil ore. It should be Late Cretaceous.

**Comment by StarStorms21** [comment]
1) Upped the chances for fossils from .30 to .40 on both fluvial and marine ores.
2) Decreased the cobble drops.
3) @Totemaster Needs some clarification, pls

4) Time periods have been fixed!
